// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA7jP8RxnuXb1h-l1HE4jlnu4lq9Lwg1Y',
    appId: '1:729299823383:web:3e78435dc1a362613fe552',
    messagingSenderId: '729299823383',
    projectId: 'movies-app-9ccbc',
    authDomain: 'movies-app-9ccbc.firebaseapp.com',
    storageBucket: 'movies-app-9ccbc.firebasestorage.app',
    measurementId: 'G-HG6PH5PXR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9LWyw4lZrQcty-qSay7HK318u3q83co',
    appId: '1:729299823383:android:4107cb4fc43622663fe552',
    messagingSenderId: '729299823383',
    projectId: 'movies-app-9ccbc',
    storageBucket: 'movies-app-9ccbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2A3pAUmxZZxlmcQ6FdnQiloBimOZuSZ0',
    appId: '1:729299823383:ios:6efaa083391cb6f43fe552',
    messagingSenderId: '729299823383',
    projectId: 'movies-app-9ccbc',
    storageBucket: 'movies-app-9ccbc.firebasestorage.app',
    iosClientId: '729299823383-49k1m217jq96bjfhroeil9d65mpcpfrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA7jP8RxnuXb1h-l1HE4jlnu4lq9Lwg1Y',
    appId: '1:729299823383:web:d9277c1f0e294b873fe552',
    messagingSenderId: '729299823383',
    projectId: 'movies-app-9ccbc',
    authDomain: 'movies-app-9ccbc.firebaseapp.com',
    storageBucket: 'movies-app-9ccbc.firebasestorage.app',
    measurementId: 'G-G5GSC991MW',
  );
}
